mot17:
  cache_dir: /ssd_4TB/divake/temporal_uncertainty/yolo_cache/data/mot17/yolov8n
  sequences:
    MOT17-02: MOT17-02-FRCNN.npz
    MOT17-04: MOT17-04-FRCNN.npz
    MOT17-05: MOT17-05-FRCNN.npz
    MOT17-09: MOT17-09-FRCNN.npz
    MOT17-10: MOT17-10-FRCNN.npz
    MOT17-11: MOT17-11-FRCNN.npz
    MOT17-13: MOT17-13-FRCNN.npz
  selected_sequence: MOT17-13-FRCNN
  split:
    ratio: 0.5
    random_seed: 42
  filters:
    confidence_threshold: 0.3
    layer_id: 21
