experiment:
  name: aleatoric_mot17_11
  description: Mahalanobis-based aleatoric uncertainty on MOT17-11
  output:
    results_dir: results/aleatoric_mot17_13
    plots_dir: results/aleatoric_mot17_13/plots
    save_intermediate: true
  evaluation:
    metrics:
    - pearson
    - spearman
    analyze_by_confidence: true
    analyze_by_iou: true
  visualization:
    dpi: 150
    style: default
    save_format: png
